### ISSUE TITLE
Thumbnail for the same map is different when browsed from different entry points

### ISSUE THREAD

**Issue by wendy-guan** [cga-harvard/CAMP#13]
Thumbnails for the same map look different when browsed from different entry points. For example, map # 825, if you search for it, you see its thumbnail shows big triangles on OSM background; but if you browse it from http://128.31.22.46/maps/?limit=20&offset=0 (very bottom of the page), its thumbnail shows small triangles on satellite background. Please make the thumbnail consistent for the same map.

**Comment by capooti** [comment]
thanks for reporting this @wendy-guan 
basically it looks like that when there is some search criteria applied to the list, the curated thumbnails are not used
will fix it early next week (easy one)

**Comment by capooti** [comment]
This looks fixed now. @wendy-guan you can close it once you confirm it

**Comment by wendy-guan** [comment]
They still look like before (different) even after I cleared my browser cache.

**Comment by capooti** [comment]
I currently see this: http://recordit.co/WbhA7T7bxm
should curated thumbnails behave differently?

**Comment by wendy-guan** [comment]
When I enter that map name into home page's search box, I still see the old thumbnail with large triangles on OSM.  http://128.31.22.46/search/?title__icontains=%E4%B8%BD%E6%B0%B4%E4%B9%9D%E5%B8%82%E5%8E%BF%E9%A3%8E%E5%85%89%E7%89%87%E9%9B%86%E9%94%A6&limit=20&offset=0

**Comment by capooti** [comment]
ok so this is happening only from the main search text box. I will look into this, it is very likely that is not using the correct API. I have checked all the other entry points and they look correctly working.
